# Generated by Django 5.2.6 on 2025-09-24 05:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Введите текст вопроса", verbose_name="Текст вопроса"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Время создания вопроса",
                        verbose_name="Дата создания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        help_text="Уникальный идентификатор пользователя (например, UUID)",
                        max_length=255,
                        verbose_name="ID пользователя",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Введите текст ответа", verbose_name="Текст ответа"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Время создания ответа",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        help_text="Вопрос, на который дан ответ",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="askme.question",
                        verbose_name="Вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ",
                "verbose_name_plural": "Ответы",
                "ordering": ["-created_at"],
            },
        ),
    ]
