# Generated by Django 5.2.6 on 2025-09-24 05:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("askme", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="user_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Уникальный идентификатор пользователя (UUID)",
                verbose_name="ID пользователя",
            ),
        ),
    ]
